// src/features/enrollment/steps.ts

import { StepDef } from "./types";
import {
  User,
  Phone,
  Briefcase,
  Wallet,
  Calendar,
  FileText,
  MapPin,
  LayoutDashboard,
  Laptop,
  FolderOpen,
 Eye,
  Heart,
  GraduationCap,
} from "lucide-react";
export const quickFormSteps: StepDef[] = [
  {
    id: "identity",
    title: "Identity & Basic Info",
    subtitle: "Personal identification as per CNIC",
    icon: User,
    fields: [
    
      {
        key: "first_name",
        name: "First Name",
        type: "text",
        required: true,
        placeholder: "As per CNIC",
        compliance: "NADRA",
      },
      {
        key: "last_name",
        name: "Last Name",
        type: "text",
        required: true,
        placeholder: "As per CNIC",
        compliance: "NADRA",
      },
      {
        key: "father_or_husband_name",
        name: "Father's/Husband's Name",
        type: "text",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "date_of_birth",
        name: "Date of Birth",
        type: "date",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "gender",
        name: "Gender",
        type: "select",
        required: true,
        options: ["Male", "Female", "Other"],
        compliance: "SS",
      },
      {
        key: "cnic_number",
        name: "CNIC Number",
        type: "text",
        required: true,
        placeholder: "XXXXX-XXXXXXX-X",
        compliance: "NADRA",
      },
      {
        key: "cnic_issue_date",
        name: "CNIC Issue Date",
        type: "date",
        required: true,
      },
      {
        key: "cnic_expiry_date",
        name: "CNIC Expiry Date",
        type: "date",
        required: true,
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Information",
    subtitle: "Communication and emergency details",
    icon: Phone,
    fields: [
      {
        key: "mobile_number",
        name: "Mobile Number",
        type: "tel",
        required: true,
        placeholder: "03XX-XXXXXXX",
      },
      {
        key: "personal_email",
        name: "Personal Email",
        type: "email",
        required: false,
        placeholder: "name@email.com",
      },
      {
        key: "current_address",
        name: "Current Address",
        type: "textarea",
        required: true,
        placeholder: "House #, Street, Area, City",
        compliance: "EOBI",
      },
      {
        key: "permanent_address",
        name: "Permanent Address",
        type: "textarea",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "emergency_contact_name",
        name: "Emergency Contact Name",
        type: "text",
        required: true,
        compliance: "Safety",
      },
      {
        key: "emergency_contact_phone",
        name: "Emergency Contact Phone",
        type: "tel",
        required: true,
      },
      {
        key: "emergency_relation",
        name: "Emergency Relation",
        type: "select",
        required: true,
        options: ["Father", "Mother", "Spouse", "Sibling", "Friend"],
      },
    ],
  },
  {
    id: "employment",
    title: "Employment Details",
    subtitle: "Job position and organization",
    icon: Briefcase,
    fields: [
      {
        key: "date_of_joining",
        name: "Date of Joining",
        type: "date",
        required: true,
      },
      {
        key: "company",
        name: "Company",
        type: "select",
        required: true,
        options: ["Flexi IT Services", "HR Perfect Solutions"],
        compliance: "EOBI",
      },
      {
        key: "branch_location",
        name: "Branch/Location",
        type: "select",
        required: true,
        options: ["Head Office - Lahore", "Karachi", "Islamabad"],
      },
      {
        key: "department",
        name: "Department",
        type: "select",
        required: true,
        options: ["Engineering", "Product", "Sales", "HR", "Finance", "Operations"],
      },
      {
        key: "designation",
        name: "Designation",
        type: "select",
        required: true,
        options: ["Director", "Manager", "Team Lead", "Senior Executive", "Executive"],
        compliance: "Standing Orders",
      },
      {
        key: "employment_class",
        name: "Employment Class",
        type: "select",
        required: true,
        options: ["White Collar", "Blue Collar", "Labor", "Contractual", "Intern"],
      },
      {
        key: "employment_type",
        name: "Employment Type",
        type: "select",
        required: true,
        options: ["Permanent", "Probation", "Contract", "Daily Wage"],
      },
      {
        key: "reporting_manager",
        name: "Reporting Manager",
        type: "select",
        required: true,
        options: ["Select manager..."],
      },
      {
        key: "probation_months",
        name: "Probation (months)",
        type: "number",
        required: true,
        placeholder: "3",
      },
      {
        key: "notice_period_days",
        name: "Notice Period (days)",
        type: "number",
        required: true,
       placeholder: "30",
      },
    ],
  },
  {
    id: "salary",
    title: "Salary & Statutory",
    subtitle: "Compensation and compliance",
    icon: Wallet,
    fields: [
      {
        key: "basic_salary_pkr",
        name: "Basic Salary (PKR)",
        type: "number",
        required: true,
        placeholder: "Min. Rs. 37,000",
        compliance: "Min Wage",
      },
      {
        key: "salary_mode",
        name: "Salary Mode",
        type: "select",
        required: true,
        options: ["Bank Transfer", "Mobile Wallet", "Cash", "Cheque"],
      },
      {
        key: "bank_name",
        name: "Bank Name",
        type: "select",
        required: false,
        options: ["HBL", "MCB", "UBL", "Allied Bank", "Meezan", "Bank Alfalah"],
      },
      {
        key: "bank_account_iban",
        name: "Bank Account / IBAN",
        type: "text",
        required: false,
        placeholder: "PK00XXXX0000000000000000",
      },
      {
        key: "account_title",
        name: "Account Title",
        type: "text",
        required: false,
      },
      {
        key: "ntn",
        name: "NTN",
        type: "text",
        required: true,
        placeholder: "0000000-0",
        compliance: "FBR",
      },
      {
        key: "filer_status",
        name: "Filer Status",
        type: "select",
        required: true,
        options: ["Filer", "Non-Filer", "Late Filer"],
        compliance: "FBR",
      },
      {
        key: "eobi_uan",
        name: "EOBI UAN",
        type: "text",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "eobi_registration_date",
        name: "EOBI Registration Date",
        type: "date",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "ss_number",
        name: "PESSI/SESSI Number",
        type: "text",
        required: true,
        compliance: "SS",
      },
      {
        key: "ss_province",
        name: "SS Province",
        type: "select",
        required: true,
        options: ["Punjab (PESSI)", "Sindh (SESSI)", "KPK", "Balochistan"],
      },
      {
        key: "ss_registration_date",
        name: "SS Registration Date",
        type: "date",
        required: true,
      },
    ],
  },
  {
    id: "attendance",
    title: "Attendance & Leaves",
    subtitle: "Work schedule and entitlements",
    icon: Calendar,
    fields: [
      {
        key: "default_shift",
        name: "Default Shift",
        type: "select",
        required: true,
        options: ["General (9-6)", "Morning", "Evening", "Night", "Flexible"],
      },
      {
        key: "weekly_off_pattern",
        name: "Weekly Off Pattern",
        type: "select",
        required: true,
        options: ["Sunday Only", "Sat-Sun", "Friday Only", "Rotating"],
      },
      {
        key: "leave_policy",
        name: "Leave Policy",
        type: "select",
        required: true,
        options: ["Standard (14 AL + 10 CL)", "Senior (21 AL)", "Executive (30 AL)"],
      },
      {
        key: "holiday_list",
        name: "Holiday List",
        type: "select",
        required: true,
        options: ["Pakistan Federal 2025", "Punjab Provincial", "Sindh Provincial"],
      },
      {
        key: "overtime_eligible",
        name: "Overtime Eligible",
        type: "checkbox",
        required: false,
        label: "Employee is eligible for overtime pay",
      },
    ],
  },
  {
    id: "documents",
    title: "Documents & Consent",
    subtitle: "Required uploads and agreements",
    icon: FileText,
    fields: [
      {
        key: "cnic_front_image",
        name: "CNIC Front Image",
        type: "file",
        required: true,
        compliance: "NADRA",
      },
      {
        key: "cnic_back_image",
        name: "CNIC Back Image",
        type: "file",
        required: true,
        compliance: "NADRA",
      },
      {
        key: "passport_size_photo",
        name: "Passport Size Photo",
        type: "file",
        required: true,
      },
      {
        key: "e_consent_data_accuracy",
        name: "E-Consent: Data Accuracy",
        type: "checkbox",
        required: true,
        label: "I confirm all information is accurate and true",
      },
      {
        key: "e_consent_background_check",
        name: "E-Consent: Background Check",
        type: "checkbox",
        required: true,
        label: "I authorize background verification checks",
      },
      {
        key: "code_of_conduct",
        name: "Code of Conduct",
        type: "checkbox",
        required: true,
        label: "I agree to abide by the Company Code of Conduct",
      },
    ],
  },
  {
    id: "submit",
    title: "Submit",
    subtitle: "Review everything before final submit",
    icon: Eye,
    fields: [], // IMPORTANT: keep empty
  },
];



export const detailedFormSteps: StepDef[] = [
  {
    id: "overview",
    title: "Overview",
    subtitle: "Core identity and employment",
    icon: LayoutDashboard,
    fields: [
    
      {
        key: "first_name",
        name: "First Name",
        type: "text",
        required: true,
        placeholder: "As per CNIC",
        compliance: "NADRA",
      },
      {
        key: "middle_name",
        name: "Middle Name",
        type: "text",
        required: false,
      },
      {
        key: "last_name",
        name: "Last Name",
        type: "text",
        required: true,
        compliance: "NADRA",
      },
      {
        key: "father_or_husband_name",
        name: "Father's/Husband's Name",
        type: "text",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "date_of_birth",
        name: "Date of Birth",
        type: "date",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "gender",
        name: "Gender",
        type: "select",
        required: true,
        options: ["Male", "Female", "Other"],
      },
      {
        key: "cnic_number",
        name: "CNIC Number",
        type: "text",
        required: true,
        placeholder: "XXXXX-XXXXXXX-X",
        compliance: "NADRA",
      },
      {
        key: "cnic_issue_date",
        name: "CNIC Issue Date",
        type: "date",
        required: true,
      },
      {
        key: "cnic_expiry_date",
        name: "CNIC Expiry Date",
        type: "date",
        required: true,
      },
      {
        key: "date_of_joining",
        name: "Date of Joining",
        type: "date",
        required: true,
      },
      {
        key: "company",
        name: "Company",
        type: "select",
        required: true,
        options: ["Flexi IT Services", "HR Perfect Solutions"],
      },
      {
        key: "department",
        name: "Department",
        type: "select",
        required: true,
        options: ["Engineering", "Product", "Sales", "HR", "Finance"],
      },
      {
        key: "designation",
        name: "Designation",
        type: "select",
        required: true,
        options: ["Director", "Manager", "Team Lead", "Executive"],
      },
      {
        key: "employment_class",
        name: "Employment Class",
        type: "select",
        required: true,
        options: ["White Collar", "Blue Collar", "Labor", "Intern"],
      },
    ],
  },

  {
    id: "address",
    title: "Address & Contacts",
    subtitle: "Complete address and communication",
    icon: MapPin,
    fields: [
      {
        key: "mobile_primary",
        name: "Mobile (Primary)",
        type: "tel",
        required: true,
        placeholder: "03XX-XXXXXXX",
      },
      {
        key: "mobile_secondary",
        name: "Mobile (Secondary)",
        type: "tel",
        required: false,
      },
      {
        key: "landline",
        name: "Landline",
        type: "tel",
        required: false,
      },
      {
        key: "personal_email",
        name: "Personal Email",
        type: "email",
        required: false,
      },
      {
        key: "company_email",
        name: "Company Email",
        type: "email",
        required: false,
        disabled: true,
      },

      {
        key: "current_address_line_1",
        name: "Current Address Line 1",
        type: "text",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "current_address_line_2",
        name: "Current Address Line 2",
        type: "text",
        required: false,
      },
      {
        key: "current_city",
        name: "Current City",
        type: "select",
        required: true,
        options: [
          "Lahore",
          "Karachi",
          "Islamabad",
          "Rawalpindi",
          "Faisalabad",
          "Other",
        ],
      },
      {
        key: "current_province",
        name: "Current Province",
        type: "select",
        required: true,
        options: ["Punjab", "Sindh", "KPK", "Balochistan", "Islamabad"],
      },
      {
        key: "current_postal_code",
        name: "Current Postal Code",
        type: "text",
        required: false,
      },
      {
        key: "residing_since",
        name: "Residing Since",
        type: "date",
        required: false,
      },
      {
        key: "residence_type",
        name: "Residence Type",
        type: "select",
        required: false,
        options: ["Owned", "Rented", "Company", "Family"],
      },

      {
        key: "permanent_address_line_1",
        name: "Permanent Address Line 1",
        type: "text",
        required: true,
      },
      {
        key: "permanent_address_line_2",
        name: "Permanent Address Line 2",
        type: "text",
        required: false,
      },
      {
        key: "permanent_city",
        name: "Permanent City",
        type: "select",
        required: true,
        options: ["Lahore", "Karachi", "Islamabad", "Rawalpindi", "Other"],
      },
      {
        key: "permanent_province",
        name: "Permanent Province",
        type: "select",
        required: true,
        options: ["Punjab", "Sindh", "KPK", "Balochistan"],
      },

      {
        key: "emergency_1_name",
        name: "Emergency #1 Name",
        type: "text",
        required: true,
        compliance: "Safety",
      },
      {
        key: "emergency_1_phone",
        name: "Emergency #1 Phone",
        type: "tel",
        required: true,
      },
      {
        key: "emergency_1_relation",
        name: "Emergency #1 Relation",
        type: "select",
        required: true,
        options: ["Father", "Mother", "Spouse", "Sibling", "Friend"],
      },
      {
        key: "emergency_1_address",
        name: "Emergency #1 Address",
        type: "textarea",
        required: false,
      },

      {
        key: "emergency_2_name",
        name: "Emergency #2 Name",
        type: "text",
        required: false,
      },
      {
        key: "emergency_2_phone",
        name: "Emergency #2 Phone",
        type: "tel",
        required: false,
      },
      {
        key: "emergency_2_relation",
        name: "Emergency #2 Relation",
        type: "select",
        required: false,
        options: ["Father", "Mother", "Spouse", "Sibling"],
      },
    ],
  },

  {
    id: "attendance",
    title: "Attendance & Leaves",
    subtitle: "Work schedule and leave config",
    icon: Calendar,
    fields: [
      {
        key: "branch_location",
        name: "Branch/Location",
        type: "select",
        required: true,
        options: ["Head Office", "Karachi", "Islamabad", "Remote"],
      },
      {
        key: "default_shift",
        name: "Default Shift",
        type: "select",
        required: true,
        options: ["General (9-6)", "Morning", "Evening", "Night", "Flexible"],
      },
      {
        key: "shift_start_time",
        name: "Shift Start Time",
        type: "text",
        required: false,
        placeholder: "09:00 AM",
      },
      {
        key: "shift_end_time",
        name: "Shift End Time",
        type: "text",
        required: false,
        placeholder: "06:00 PM",
      },
      {
        key: "break_duration_mins",
        name: "Break Duration (mins)",
        type: "number",
        required: false,
        placeholder: "60",
      },
      {
        key: "weekly_off_pattern",
        name: "Weekly Off Pattern",
        type: "select",
        required: true,
        options: ["Sunday Only", "Sat-Sun", "Friday Only", "Rotating"],
      },
      {
        key: "roster_pattern",
        name: "Roster Pattern",
        type: "select",
        required: false,
        options: ["Fixed", "Weekly Rotating", "Monthly Rotating"],
      },
      {
        key: "leave_policy",
        name: "Leave Policy",
        type: "select",
        required: true,
        options: ["Standard", "Senior", "Executive", "Contractual"],
      },
      {
        key: "holiday_list",
        name: "Holiday List",
        type: "select",
        required: true,
        options: ["Pakistan Federal 2025", "Punjab", "Sindh"],
      },
      {
        key: "leave_approver",
        name: "Leave Approver",
        type: "select",
        required: true,
        options: ["Direct Manager", "Dept Head", "HR Manager"],
      },
      {
        key: "attendance_approver",
        name: "Attendance Approver",
        type: "select",
        required: false,
        options: ["Direct Manager", "HR Manager"],
      },
      {
        key: "biometric_device_id",
        name: "Biometric Device ID",
        type: "text",
        required: false,
      },
      {
        key: "biometric_enrollment_date",
        name: "Biometric Enrollment Date",
        type: "date",
        required: false,
      },
      {
        key: "face_recognition",
        name: "Face Recognition",
        type: "checkbox",
        required: false,
        label: "Enrolled in facial recognition",
      },
      {
        key: "overtime_eligible",
        name: "Overtime Eligible",
        type: "checkbox",
        required: false,
        label: "Eligible for overtime pay",
      },
      {
        key: "flexible_timing",
        name: "Flexible Timing",
        type: "checkbox",
        required: false,
        label: "Flexible arrival/departure",
      },
      {
        key: "remote_work_allowed",
        name: "Remote Work Allowed",
        type: "checkbox",
        required: false,
        label: "Permitted to work remotely",
      },
    ],
  },

  {
    id: "salary",
    title: "Salary & Statutory",
    subtitle: "Compensation and compliance",
    icon: Wallet,
    fields: [
      {
        key: "basic_salary_pkr",
        name: "Basic Salary (PKR)",
        type: "number",
        required: true,
        placeholder: "Min. Rs. 37,000",
        compliance: "Min Wage",
      },
      {
        key: "gross_salary_pkr",
        name: "Gross Salary (PKR)",
        type: "number",
        required: false,
      },
      {
        key: "currency",
        name: "Currency",
        type: "select",
        required: true,
        options: ["PKR", "USD", "AED", "GBP"],
      },
      {
        key: "pay_frequency",
        name: "Pay Frequency",
        type: "select",
        required: true,
        options: ["Monthly", "Bi-Weekly", "Weekly"],
      },
      {
        key: "pay_cutoff_day",
        name: "Pay Cut-off Day",
        type: "number",
        required: false,
        placeholder: "1-28",
      },
      {
        key: "salary_mode",
        name: "Salary Mode",
        type: "select",
        required: true,
        options: ["Bank", "Mobile Wallet", "Cash", "Cheque"],
      },
      {
        key: "bank_name",
        name: "Bank Name",
        type: "select",
        required: false,
        options: ["HBL", "MCB", "UBL", "Allied", "Meezan", "Alfalah"],
      },
      {
        key: "branch_name",
        name: "Branch Name",
        type: "text",
        required: false,
      },
      {
        key: "account_number",
        name: "Account Number",
        type: "text",
        required: false,
      },
      {
        key: "iban",
        name: "IBAN",
        type: "text",
        required: false,
        placeholder: "PK00XXXX...",
      },
      {
        key: "account_title",
        name: "Account Title",
        type: "text",
        required: false,
      },
      {
        key: "wallet_provider",
        name: "Wallet Provider",
        type: "select",
        required: false,
        options: ["JazzCash", "Easypaisa", "NayaPay", "SadaPay"],
      },
      {
        key: "wallet_number",
        name: "Wallet Number",
        type: "text",
        required: false,
      },
      {
        key: "ntn",
        name: "NTN",
        type: "text",
        required: true,
        placeholder: "0000000-0",
        compliance: "FBR",
      },
      {
        key: "filer_status",
        name: "Filer Status",
        type: "select",
        required: true,
        options: ["Filer", "Non-Filer"],
        compliance: "FBR",
      },
      {
        key: "tax_exemption",
        name: "Tax Exemption",
        type: "checkbox",
        required: false,
        label: "Has tax exemption certificate",
      },
      {
        key: "eobi_uan",
        name: "EOBI UAN",
        type: "text",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "eobi_reg_date",
        name: "EOBI Reg Date",
        type: "date",
        required: true,
        compliance: "EOBI",
      },
      {
        key: "previous_eobi_employer",
        name: "Previous EOBI Employer",
        type: "text",
        required: false,
      },
      {
        key: "ss_number",
        name: "PESSI/SESSI Number",
        type: "text",
        required: true,
        compliance: "SS",
      },
      {
        key: "ss_province",
        name: "SS Province",
        type: "select",
        required: true,
        options: ["Punjab (PESSI)", "Sindh (SESSI)", "KPK", "Balochistan"],
      },
      {
        key: "ss_reg_date",
        name: "SS Reg Date",
        type: "date",
        required: true,
      },
      {
        key: "gratuity_applicable",
        name: "Gratuity Applicable",
        type: "checkbox",
        required: false,
        label: "Eligible for gratuity",
      },
      {
        key: "pf_applicable",
        name: "PF Applicable",
        type: "checkbox",
        required: false,
        label: "Enrolled in Provident Fund",
      },
    ],
  },

  {
    id: "personal",
    title: "Personal Details",
    subtitle: "Personal info, health, family",
    icon: Heart,
    fields: [
      {
        key: "marital_status",
        name: "Marital Status",
        type: "select",
        required: false,
        options: ["Single", "Married", "Divorced", "Widowed"],
      },
      {
        key: "spouse_name",
        name: "Spouse Name",
        type: "text",
        required: false,
      },
      {
        key: "marriage_date",
        name: "Marriage Date",
        type: "date",
        required: false,
      },
      {
        key: "number_of_children",
        name: "Number of Children",
        type: "number",
        required: false,
      },
      {
        key: "number_of_dependents",
        name: "Number of Dependents",
        type: "number",
        required: false,
      },
      {
        key: "blood_group",
        name: "Blood Group",
        type: "select",
        required: false,
        options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
      },
      {
        key: "religion",
        name: "Religion",
        type: "select",
        required: false,
        options: ["Islam", "Christianity", "Hinduism", "Other"],
      },
      {
        key: "nationality",
        name: "Nationality",
        type: "select",
        required: false,
        options: ["Pakistani", "Other"],
      },
      {
        key: "domicile_province",
        name: "Domicile Province",
        type: "select",
        required: false,
        options: ["Punjab", "Sindh", "KPK", "Balochistan", "Islamabad"],
      },
      {
        key: "domicile_district",
        name: "Domicile District",
        type: "text",
        required: false,
      },
      {
        key: "medical_fitness_date",
        name: "Medical Fitness Date",
        type: "date",
        required: false,
        compliance: "Safety",
      },
      {
        key: "medical_validity",
        name: "Medical Validity",
        type: "date",
        required: false,
      },
      {
        key: "medical_conditions",
        name: "Medical Conditions",
        type: "textarea",
        required: false,
        placeholder: "Allergies, conditions...",
      },
      {
        key: "disability_status",
        name: "Disability Status",
        type: "checkbox",
        required: false,
        label: "Person with Disability",
      },
      {
        key: "disability_type",
        name: "Disability Type",
        type: "text",
        required: false,
      },
      {
        key: "insurance_provider",
        name: "Insurance Provider",
        type: "select",
        required: false,
        options: ["None", "Jubilee", "Adamjee", "EFU", "State Life"],
      },
      {
        key: "insurance_policy_number",
        name: "Insurance Policy #",
        type: "text",
        required: false,
      },
      {
        key: "coverage_pkr",
        name: "Coverage (PKR)",
        type: "number",
        required: false,
      },
      {
        key: "passport_number",
        name: "Passport Number",
        type: "text",
        required: false,
      },
      {
        key: "passport_issue_date",
        name: "Passport Issue Date",
        type: "date",
        required: false,
      },
      {
        key: "passport_expiry",
        name: "Passport Expiry",
        type: "date",
        required: false,
      },
      {
        key: "passport_issue_place",
        name: "Passport Issue Place",
        type: "text",
        required: false,
      },
      {
        key: "driving_license",
        name: "Driving License",
        type: "text",
        required: false,
      },
      {
        key: "license_expiry",
        name: "License Expiry",
        type: "date",
        required: false,
      },
      {
        key: "shirt_size",
        name: "Shirt Size",
        type: "select",
        required: false,
        options: ["XS", "S", "M", "L", "XL", "XXL"],
      },
      {
        key: "trouser_size",
        name: "Trouser Size",
        type: "text",
        required: false,
      },
      {
        key: "shoe_size",
        name: "Shoe Size",
        type: "text",
        required: false,
      },
    ],
  },

  {
    id: "profile",
    title: "Profile & Experience",
    subtitle: "Education and work history",
    icon: GraduationCap,
    fields: [
      {
        key: "professional_summary",
        name: "Professional Summary",
        type: "textarea",
        required: false,
        placeholder: "Brief background...",
      },
      {
        key: "linkedin_profile",
        name: "LinkedIn Profile",
        type: "text",
        required: false,
      },
      {
        key: "highest_education",
        name: "Highest Education",
        type: "select",
        required: false,
        options: ["Matric", "Inter", "Bachelors", "Masters", "PhD", "Other"],
      },
      {
        key: "degree_title",
        name: "Degree Title",
        type: "text",
        required: false,
        placeholder: "e.g., BS Computer Science",
      },
      {
        key: "institution_name",
        name: "Institution Name",
        type: "text",
        required: false,
      },
      {
        key: "year_of_passing",
        name: "Year of Passing",
        type: "number",
        required: false,
      },
      {
        key: "grade_cgpa",
        name: "Grade/CGPA",
        type: "text",
        required: false,
      },
      {
        key: "education_field",
        name: "Education Field",
        type: "select",
        required: false,
        options: ["CS", "Engineering", "Business", "Commerce", "Arts", "Medical"],
      },
      {
        key: "second_degree",
        name: "Second Degree",
        type: "text",
        required: false,
      },
      {
        key: "second_institution",
        name: "Second Institution",
        type: "text",
        required: false,
      },
      {
        key: "second_year",
        name: "Second Year",
        type: "number",
        required: false,
      },
      {
        key: "certifications",
        name: "Certifications",
        type: "textarea",
        required: false,
      },
      {
        key: "total_experience_years",
        name: "Total Experience (Years)",
        type: "number",
        required: false,
      },
      {
        key: "previous_company_1",
        name: "Previous Company 1",
        type: "text",
        required: false,
      },
      {
        key: "previous_designation_1",
        name: "Previous Designation 1",
        type: "text",
        required: false,
      },
      {
        key: "previous_duration_1",
        name: "Previous Duration 1",
        type: "text",
        required: false,
        placeholder: "Jan 2020 - Dec 2023",
      },
      {
        key: "previous_salary_1",
        name: "Previous Salary 1",
        type: "number",
        required: false,
      },
      {
        key: "reason_for_leaving_1",
        name: "Reason for Leaving 1",
        type: "select",
        required: false,
        options: ["Career Growth", "Better Opportunity", "Relocation", "Personal"],
      },
      {
        key: "previous_company_2",
        name: "Previous Company 2",
        type: "text",
        required: false,
      },
      {
        key: "previous_designation_2",
        name: "Previous Designation 2",
        type: "text",
        required: false,
      },
      {
        key: "previous_duration_2",
        name: "Previous Duration 2",
        type: "text",
        required: false,
      },
      {
        key: "reference_1_name",
        name: "Reference 1 Name",
        type: "text",
        required: false,
      },
      {
        key: "reference_1_contact",
        name: "Reference 1 Contact",
        type: "text",
        required: false,
      },
      {
        key: "reference_1_relation",
        name: "Reference 1 Relation",
        type: "text",
        required: false,
        placeholder: "e.g., Former Manager",
      },
      {
        key: "reference_2_name",
        name: "Reference 2 Name",
        type: "text",
        required: false,
      },
      {
        key: "reference_2_contact",
        name: "Reference 2 Contact",
        type: "text",
        required: false,
      },
      {
        key: "skills_expertise",
        name: "Skills & Expertise",
        type: "textarea",
        required: false,
      },
      {
        key: "languages_known",
        name: "Languages Known",
        type: "text",
        required: false,
        placeholder: "English, Urdu, Punjabi...",
      },
    ],
  },

  {
    id: "assets",
    title: "Assets & IT Access",
    subtitle: "Equipment and credentials",
    icon: Laptop,
    fields: [
      {
        key: "company_id_card_number",
        name: "Company ID Card #",
        type: "text",
        required: false,
      },
      {
        key: "id_issue_date",
        name: "ID Issue Date",
        type: "date",
        required: false,
      },
      {
        key: "id_expiry_date",
        name: "ID Expiry Date",
        type: "date",
        required: false,
      },
      {
        key: "access_card_rfid",
        name: "Access Card / RFID",
        type: "text",
        required: false,
      },
      {
        key: "building_access_level",
        name: "Building Access Level",
        type: "select",
        required: false,
        options: ["General", "Restricted", "Server Room", "Executive", "All"],
      },
      {
        key: "parking_assigned",
        name: "Parking Assigned",
        type: "checkbox",
        required: false,
        label: "Has assigned parking",
      },
      {
        key: "parking_slot_number",
        name: "Parking Slot #",
        type: "text",
        required: false,
      },
      {
        key: "email_account",
        name: "Email Account",
        type: "email",
        required: false,
        disabled: true,
      },
      {
        key: "ad_username",
        name: "AD Username",
        type: "text",
        required: false,
      },
      {
        key: "vpn_access",
        name: "VPN Access",
        type: "checkbox",
        required: false,
        label: "VPN enabled",
      },
      {
        key: "erp_access",
        name: "ERP Access",
        type: "checkbox",
        required: false,
        label: "ERP system access",
      },
      {
        key: "hrms_self_service",
        name: "HRMS Self-Service",
        type: "checkbox",
        required: false,
        label: "HRMS portal access",
      },
      {
        key: "company_sim_number",
        name: "Company SIM #",
        type: "text",
        required: false,
      },
      {
        key: "sim_provider",
        name: "SIM Provider",
        type: "select",
        required: false,
        options: ["Jazz", "Telenor", "Zong", "Ufone"],
      },
      {
        key: "monthly_limit_pkr",
        name: "Monthly Limit (PKR)",
        type: "number",
        required: false,
      },

      {
        key: "asset_1_category",
        name: "Asset 1 Category",
        type: "select",
        required: false,
        options: ["Laptop", "Desktop", "Monitor", "Mobile", "Tablet", "Vehicle", "Other"],
      },
      {
        key: "asset_1_brand_model",
        name: "Asset 1 Brand/Model",
        type: "text",
        required: false,
        placeholder: "Dell Latitude 5540",
      },
      {
        key: "asset_1_serial_number",
        name: "Asset 1 Serial #",
        type: "text",
        required: false,
      },
      {
        key: "asset_1_tag_number",
        name: "Asset 1 Tag #",
        type: "text",
        required: false,
      },
      {
        key: "asset_1_condition",
        name: "Asset 1 Condition",
        type: "select",
        required: false,
        options: ["New", "Excellent", "Good", "Fair"],
      },
      {
        key: "asset_1_issue_date",
        name: "Asset 1 Issue Date",
        type: "date",
        required: false,
      },

      {
        key: "asset_2_category",
        name: "Asset 2 Category",
        type: "select",
        required: false,
        options: ["Laptop", "Desktop", "Monitor", "Mobile", "Other"],
      },
      {
        key: "asset_2_brand_model",
        name: "Asset 2 Brand/Model",
        type: "text",
        required: false,
      },
      {
        key: "asset_2_serial_number",
        name: "Asset 2 Serial #",
        type: "text",
        required: false,
      },

      {
        key: "vehicle_assigned",
        name: "Vehicle Assigned",
        type: "checkbox",
        required: false,
        label: "Company vehicle assigned",
      },
      {
        key: "vehicle_registration",
        name: "Vehicle Registration",
        type: "text",
        required: false,
      },
      {
        key: "vehicle_model",
        name: "Vehicle Model",
        type: "text",
        required: false,
      },
    ],
  },

  {
    id: "documents",
    title: "Documents & Consent",
    subtitle: "Uploads and acknowledgments",
    icon: FolderOpen,
    fields: [
      {
        key: "cnic_front_image",
        name: "CNIC Front Image",
        type: "file",
        required: true,
        compliance: "NADRA",
      },
      {
        key: "cnic_back_image",
        name: "CNIC Back Image",
        type: "file",
        required: true,
        compliance: "NADRA",
      },
      {
        key: "passport_size_photo",
        name: "Passport Size Photo",
        type: "file",
        required: true,
      },
      {
        key: "matriculation_certificate",
        name: "Matriculation Certificate",
        type: "file",
        required: false,
      },
      {
        key: "intermediate_certificate",
        name: "Intermediate Certificate",
        type: "file",
        required: false,
      },
      {
        key: "degree_transcript",
        name: "Degree/Transcript",
        type: "file",
        required: false,
      },
      {
        key: "experience_letters",
        name: "Experience Letters",
        type: "file",
        required: false,
      },
      {
        key: "last_salary_slip",
        name: "Last Salary Slip",
        type: "file",
        required: false,
      },
      {
        key: "bank_statement",
        name: "Bank Statement",
        type: "file",
        required: false,
      },
      {
        key: "medical_fitness_file",
        name: "Medical Fitness",
        type: "file",
        required: false,
        compliance: "Safety",
      },
      {
        key: "police_verification",
        name: "Police Verification",
        type: "file",
        required: false,
      },
      {
        key: "passport_copy",
        name: "Passport Copy",
        type: "file",
        required: false,
      },
      {
        key: "driving_license_copy",
        name: "Driving License Copy",
        type: "file",
        required: false,
      },
      {
        key: "professional_certificates",
        name: "Professional Certificates",
        type: "file",
        required: false,
      },

      {
        key: "data_accuracy",
        name: "Data Accuracy",
        type: "checkbox",
        required: true,
        label: "I confirm all information is accurate and true",
      },
      {
        key: "background_check",
        name: "Background Check",
        type: "checkbox",
        required: true,
        label: "I authorize background verification checks",
      },
      {
        key: "data_processing",
        name: "Data Processing",
        type: "checkbox",
        required: true,
        label: "I consent to data collection and processing",
      },
      {
        key: "code_of_conduct",
        name: "Code of Conduct",
        type: "checkbox",
        required: true,
        label: "I agree to abide by the Company Code of Conduct",
      },
      {
        key: "it_policy",
        name: "IT Policy",
        type: "checkbox",
        required: false,
        label: "I agree to the IT Acceptable Use Policy",
      },
      {
        key: "nda",
        name: "NDA",
        type: "checkbox",
        required: false,
        label: "I agree to the Non-Disclosure Agreement",
      },
      {
        key: "conflict_of_interest",
        name: "Conflict of Interest",
        type: "checkbox",
        required: false,
        label: "I declare no conflict of interest",
      },
    ],
  },
];
